### PR TITLE
Image upload

### PR DESCRIPTION
**Pull request by kennethwu42**
**Description**
This pull request, fulfills Cypress testing and has a happy path that starts from login/signup and goes through most if not all buttons within the app.

**Testing/Changes** 
Testing was done manually first, then making code on a cypress testing file that recreates what a human user would do.

**Testing Steps**
Be sure to have "npm install cypress --save-dev" instaleld in the root directory. Then start both front and backend via respective npm run commands. Then in the root directory run npx cypress open. The provided files should already be set up so you can test and watch an automated user goes through the site.

**Additional Notes:**
Let me know if there is anything else that needs to be added to the test cases.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Nice job, Kenneth! The code looks clean, and it looks like the tests cover the majority of the main functionality. Towards the end, when testing the account page, I suggest also adding tests for adding a profile picture, removing a profile picture, and deleting an account. Testing the adding of a profile picture will help to ensure that the image is correctly uploaded and all UI updates accordingly, and removing the picture will verify that the default image is restored, along with the proper UI updates. Lastly, adding a test for deleting the account will verify that all associated data is removed and the user is redirected appropriately.

**Review by sofiamorris — COMMENTED** [review]
Reviewing your tests, I do not have any suggestions as this looks very thorough. You did a good job covering each path that I can think of within the application.

**Comment by anissasoungpanya** [comment]
LGTM!

**Comment by kennethwu42** [comment]
Thanks guys, I've added the additional tests.

**Pull request merged**
