### PR TITLE
favorites frontend changes

### PR DESCRIPTION
**Pull request by anissasoungpanya**
Changes to visuals to cards and title page

### CODE REVIEW

**Review by joogee — APPROVED** [review]
Changes look great

**Comment by ghost** [comment]
Looks good Anissa! Favorites page looks a lot better and the code maintained its efficiency. I have no further suggestions.

**Review by sofiamorris — APPROVED** [review]
The changes are great! The favorites page looks much more appealing to the eye now.

**Comment by anissasoungpanya** [comment]
> Changes look great

Thank you!

**Comment by anissasoungpanya** [comment]
> Looks good Anissa! Favorites page looks a lot better and the code maintained its efficiency. I have no further suggestions.

Thank you, I'm glad you think so!

**Comment by anissasoungpanya** [comment]
> The changes are great! The favorites page looks much more appealing to the eye now.

Thank you!

**Comment by kennethwu42** [comment]
Everything looks well done, nice job!

**Pull request merged**
