### PR TITLE
Clean up reviews frontend.

### LINKED ISSUE #28: Feature: Restaurant reviews page does not look good.
### Summary
Edit the review page to display restaurant information clearly to the user.

### Motivation 
1. Information is provided as a long list that users will not want to read.
2. Users will absorb the information better if it looks clear and is easy to understand.

### Propose solution
1. Highlight the most important info like cuisine and overall rating on the top of the page.
2. Add a button to see further information to make page less cluttered.
3. Show average stars as a symbol not a number.

### PR DESCRIPTION
**Pull request by sofiamorris**
### Description
Altered the restaurant reviews page to look nicer. Changed how restaurant information is accessed and where it appears on the page.

### Related Issues
Closes #28

### Changes Made
- Removed need for RestaurantDetails.jsx by merging with RestaurantReviews.jsx
- Changed the top image to match the restaurant image in the database.
- Added restaurant name and "See images" button on top of restaurant image.
- List cuisine and average stars symbol on restaurant page.
- More info button opens a frame that shows extra restaurant information.
- 
### Checklist
- [x] Code compiles without errors.
- [x] Code is linted.
- [x] Code runs without errors.

### Notes for Reviewers
- Let me know if there are ideas of how to make the "more info" frame more readable.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Great job Sofia! The code looks great and the reviews frontend seems nice and updated. I suggest to also make sure that images uploaded with the reviews aren't distorted when being displayed with the review, keeping the entire user interface clean.

**Comment by kennethwu42** [comment]
Great job Sofia, one thing I might add in fixing the "see details" part is to remove the bullet points that are on the far left side of the pop up, so that it looks cleaner and not like a bullet pointed list. Other than that it looks great.

**Review by kennethwu42 — COMMENTED** [review]
Great job Sofia, one thing I might add in fixing the "see details" part is to remove the bullet points that are on the far left side of the pop up, so that it looks cleaner and not like a bullet pointed list. Other than that it looks great.

**Comment by sofiamorris** [comment]
> Great job Sofia, one thing I might add in fixing the "see details" part is to remove the bullet points that are on the far left side of the pop up, so that it looks cleaner and not like a bullet pointed list. Other than that it looks great.

Thanks for your advice, I removed the bullet points and it looks much cleaner now!

**Comment by sofiamorris** [comment]
> Great job Sofia! The code looks great and the reviews frontend seems nice and updated. I suggest to also make sure that images uploaded with the reviews aren't distorted when being displayed with the review, keeping the entire user interface clean.

That is a good suggestion, as the images should all be the same size. I will work on implementing this before we merge the branch into main.

**Review by joogee — APPROVED** [review]
LGTM! You always pay attention to details and code is easy to follow.

**Comment by sofiamorris** [comment]
> LGTM! You always pay attention to details and code is easy to follow.

Great, thanks for reviewing this!

**Comment by anissasoungpanya** [comment]
LGTM! Great job implementing such important features like images, cuisines and average stars to improve users' experience.

**Comment by sofiamorris** [comment]
> LGTM! Great job implementing such important features like images, cuisines and average stars to improve users' experience.

Thank you for taking the time to approve my changes, glad you like them!

**Pull request closed without merging**
