### PR TITLE
Improve navbar and add account settings

### PR DESCRIPTION
**Pull request by joogee**
### Description
Adds icons and centers titls for navbar items. Adds the account settings section to the account page.

### Checklist
- [x]  Code compiles without errors.
- [x]  Code is linted.
- [x]  Code runs without errors.

### CODE REVIEW

**Review by sofiamorris — APPROVED** [review]
Good work on finishing the nav bar! I like your choices of icons to represent each page route as it is easy for users to understand.

**Review by whiniy — COMMENTED** [review]
looks good to me!

**Comment by ghost** [comment]
Nice job Joanna. Great work on adding the icons to the navbar. It really improves the overall aesthetics and usability of the navigation! For the account settings section, since only the 'Log Out' and 'Delete Account' functionalities are implemented, I suggest omitting the other buttons for now to avoid redundancy or confusion. If they are implemented in the future, they can always be added back, but for now it would help to keep the account page clean and focused.

**Comment by kennethwu42** [comment]
Great job Joanna, the navbar looks great. But as Nickaan said for our time crunch it's probably best to leave out the account settings atm.  Other than that great work

**Comment by anissasoungpanya** [comment]
Looks good to me! The layout and icons are clean and well implemented!

**Pull request merged**
