### PR TITLE
Sprint2 Updates

### LINKED ISSUE #9: Restaurants: As a student, I want to easily navigate from the food complex to specific restaurants and their details or reviews so that I can quickly find information about where to eat. Estimate: 3 hrs, Actual: 4 hrs

### LINKED ISSUE #10: Account: As a student, I want to be able to create an account using my Cal Poly student email, so that I, among other Cal Poly students, can write a review. Estimate: 4 hrs, Actual: 6 hrs

### LINKED ISSUE #11: Account: As a student, I want to remove a restaurant from my favorites so that my list reflects my current preferences. Estimate: 2 hr, Actual: 1 hr

### LINKED ISSUE #12: Account: As a PolyEats user, I want to be able to favorite certain dining places on campus, so that I can easily access the place, dish name, and dish reviews for another time. Estimate : 2 hrs, Actual: 2.5 hrs

### LINKED ISSUE #13: Account: As a student, I want to add or update my profile picture so that my account feels more personalized. Estimate: 2 hrs, Actual: 4 hrs

### LINKED ISSUE #14: Account: As a student, I want to delete my account if I no longer want to use the app so that I can ensure my data is no longer stored. Estimate: 2 hrs, Actual: 1.5 hrs

### PR DESCRIPTION
**Pull request by ghost**
### Description
This pull request introduces key features like navigation between different pages and user authentication.
Closes Issue: #9 #10 #11 #12 #13 #14 
#### User Authentication:
- Implemented login and signup functionality
- Unified login and signup processes under a shared component (Login.jsx) with conditional rendering based on the user's path.
#### Navigation Features:
- Added navigation between complexes, restaurants, and restaurant details.
- Integrated new pages for Favorites, Accounts, and Home.
### Testing
- Manually tested the login and signup flows to ensure proper user authentication.
- Verified navigation flows to ensure that the app correctly transitions between pages
#### Testing steps
1. Create an account using the signup form and verify redirection to the app's login page.
2. Log in with valid credentials and check access to protected features.
3. Navigate from a complex to its restaurants, then to individual restaurant details.
4. Test the Favorites, Accounts, and Home pages for proper rendering and navigation.
### Additional Notes
- Let me know if you run into any edge cases or issues while testing the new features.
- Most likely need to improve the logic for the account profile picture by the next sprint. UI design is also incomplete and should be done by the next sprint.

### CODE REVIEW

**Review by kennethwu42 — COMMENTED** [review]
Great work Nickaan, I ran cypress testing and went through a path that a human user would go through, and every past worked. No need to change anything here, great job!

**Review by sofiamorris — COMMENTED** [review]
The progress within this commit looks great! The pages transition smoothly and accurately throughout the application and I am successfully able to create an account and log into the website. I do not see a need for any changes to be made here before we commit to main, great job.

**Comment by ghost** [comment]
> Great work Nickaan, I ran cypress testing and went through a path that a human user would go through, and every past worked. No need to change anything here, great job!

Thanks Kenneth, I appreciate you taking the time to review and test the changes! I'm glad everything worked smoothly and passed the Cypress tests. Let me know if there's anything else I can improve!

**Comment by ghost** [comment]
> The progress within this commit looks great! The pages transition smoothly and accurately throughout the application and I am successfully able to create an account and log into the website. I do not see a need for any changes to be made here before we commit to main, great job.

Thanks for the review and feedback Sofia! I'm glad to hear the transitions and functionality worked as intended. I appreciate your time and effort in testing those features. Let me know if there's anything else to address before committing to main!

**Comment by anissasoungpanya** [comment]
Great job making navigation of the app clear and easy to navigate for users!

**Comment by ghost** [comment]
> Great job making navigation of the app clear and easy to navigate for users!

Thanks! I'm glad the navigation feels intuitive and clear. Ensuring a seamless user experience was a priority, so it's great to hear that it works well. Let me know if you notice any areas for further improvement.

**Pull request merged**
